# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'app1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for app1
	pod 'Firebase/Core'
	pod 'Firebase/Firestore'
	pod 'Firebase/Database'
	pod 'Firebase/Storage'

  target 'app1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'app1UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
